project:
  type: book

book:
  title: "Vascular Surgery Exam Prep"
  author: "Audible Bleeding"
  date: "01/03/2023"
  description: "eBook Companion for Audible Bleeding Podcast Series"
  cover-image: images/ab_examprep_cover.jpg
  chapters:
    - index.qmd
    - authors.qmd

    - part: "Head and Neck"
      chapters:
       - cerebrovascular.qmd
       - trauma-cerebrovascular.qmd

    - part: "Upper Extremity"
      chapters: 
        - upper-extremity.qmd
        - tos.qmd
        - hemodialysis.qmd
        
    - part: "Thorax"
      chapters:
        - dissection.qmd
        - taaa.qmd
        - aortopathies.qmd
        - trauma-endovascular.qmd
    
    - part: "Abdomen"
      chapters:
        - abdominal-aneurysms.qmd
        - mesenteric.qmd
        - renal.qmd
        - trauma-arterial.qmd
        - trauma-venous.qmd
         
    - part: "Lower Extremity"
      chapters:
        - claudication.qmd
        - clti.qmd
        - ali.qmd
        - venous-disease.qmd
        - trauma-peripheral.qmd
        
    - part: "General"
      chapters:
        - vascular-lab.qmd
        - endovascular.qmd

    - references.qmd

  repo-url: https://github.com/adam-mdmph/vs-examprep.git
  google-analytics: "G-T4DWNE55D1"
  cookie-consent: true
  number-sections: true
  crossref:
    chapters: true
  open-graph: true
  twitter-card:
    image: "https://raw.githubusercontent.com/adam-mdmph/vs-examprep/main/images/ab_examprep_cover.png"
  favicon: images/ab_examprep_icon.png
  
bibliography: references.bib

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: scrreprt
#    include-in-header: 
#      text: |
#        \usepackage{makeidx}
#        \makeindex
#    include-after-body: 
#      text: |
#        \printindex

editor: visual

comments: 
  hypothesis: true
  
