project:
  type: book

book:
  title: "Vascular Surgery Exam Prep"
  author: "Audible Bleeding"
  date: "10/22/2022"
  chapters:
    - index.qmd
    - authors.qmd
    - cerebrovascular.qmd
    - upper-extremity.qmd
    - hemodialysis.qmd
    - thoracic-aorta.qmd
    - abdominal-aneurysms.qmd
    - lower-extremity.qmd
    - renal.qmd
    - mesenteric.qmd
    - vascular-trauma.qmd
    - venous-disease.qmd
    - vascular-lab.qmd
    - endovascular.qmd
    - references.qmd
  repo-url: https://github.com/adam-mdmph/vs-examprep.git
  sharing: [twitter]
  google-analytics: "G-T4DWNE55D1"
  
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex

editor: visual

comments: 
  hypothesis: true
  
