project:
  type: book

book:
  title: "Vascular Surgery Exam Prep"
  author: "Adam Johnson, MD, MPH; Matt Smith, MD, PhD; and Audible Bleeding"
  date: "r Sys.Date()"
  chapters:
    - index.qmd
    - cerebrovascular.qmd
    - references.qmd
  repo-url: https://github.com/adam-mdmph/vs-examprep.git
  repo-actions: [edit, issue]
  downloads: [pdf]
  sharing: [twitter]

page-footer:
  left: |
      Editors: Adam P Johnson MD, MPH; Matt Smith MD, PhD; and <a href="https://www.audiblebleeding.com/about-1/">Audible Bleeding Team</a>.
  right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex

editor: visual

